#!/usr/bin/env node
// Walks dist/ after `vite build` and writes server/embedded-assets.js
// with every file's bytes base64-encoded so the compiled binary can serve
// the frontend without needing dist/ on disk.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const distDir = path.join(projectRoot, "dist");
const outFile = path.join(projectRoot, "server", "embedded-assets.js");

if (!fs.existsSync(distDir)) {
  console.error(`[embed-assets] ${distDir} does not exist. Run 'npm run build' first.`);
  process.exit(1);
}

// Explicit allowlist of extensions that may ship in the bundled binary.
// Sourcemaps (`.map`) deliberately excluded — they leak module structure
// and aren't needed at runtime. Anything not on the list is skipped (and a
// warning printed) so a stray `.env` / `.key` in dist/ never reaches the
// embedded payload.
const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".ico": "image/x-icon",
};

function* walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

const assets = {};
let total = 0;
let skipped = 0;
for (const abs of walk(distDir)) {
  const rel = "/" + path.relative(distDir, abs).split(path.sep).join("/");
  const ext = path.extname(abs).toLowerCase();
  if (!(ext in MIME)) {
    console.warn(
      `[embed-assets] skipping ${rel} — extension '${ext || "(none)"}' not in allowlist`,
    );
    skipped++;
    continue;
  }
  const type = MIME[ext];
  const bytes = fs.readFileSync(abs);
  total += bytes.length;
  assets[rel] = { type, b64: bytes.toString("base64") };
}

const header = `// AUTO-GENERATED by scripts/embed-assets.js — do not edit by hand.
// Contains the built frontend (dist/) embedded as base64 so the compiled
// binary can serve it without dist/ on disk.
`;

const body = `export const embeddedAssets = ${JSON.stringify(assets, null, 0)};\n`;
fs.writeFileSync(outFile, header + body);

const sizeKb = (total / 1024).toFixed(1);
const note = skipped > 0 ? ` (skipped ${skipped})` : "";
console.log(
  `[embed-assets] embedded ${Object.keys(assets).length} files (${sizeKb} KB)${note} -> ${path.relative(projectRoot, outFile)}`,
);
